apiVersion: oceanaws.crossplane.io/v1alpha1
kind: OceanAws
metadata:
  annotations:
    meta.upbound.io/example-id: oceanaws/v1alpha1/oceanaws
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    controllerId: ocean-dev
    desiredCapacity: 2
    filters:
    - architectures:
      - x86_64
      - i386
      categories:
      - Accelerated_computing
      - Compute_optimized
      diskTypes:
      - EBS
      - SSD
      excludeFamilies:
      - m*
      excludeMetal: false
      hypervisor:
      - xen
      includeFamilies:
      - c*
      - t*
      isEnaSupported: false
      maxGpu: 4
      maxMemoryGib: 16
      maxNetworkPerformance: 20
      maxVcpu: 16
      minEnis: 2
      minGpu: 0
      minMemoryGib: 8
      minNetworkPerformance: 2
      minVcpu: 2
      rootDeviceTypes:
      - ebs
      virtualizationTypes:
      - hvm
    maxSize: 2
    minSize: 1
    name: demo
    region: us-west-2
    subnetIds:
    - subnet-123456789
