apiVersion: oceanawslaunchspec.crossplane.io/v1alpha1
kind: OceanAwsLaunchSpec
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: testvng
spec:
  forProvider:
    oceanId: o-123456
    name: testvng
    strategy:
      - spotPercentage: 70
        utilizeReservedInstances: false
  providerConfigRef:
    name: default