apiVersion: crossplane-provider-spot.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: spot-creds
      namespace: crossplane-system
      key: credentials
