apiVersion: oceangke.spot.upbound.io/v1alpha1
kind: OceanGke
metadata:
  annotations:
    meta.upbound.io/example-id: oceangke/v1alpha1/oceangke
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendServices:
    - locationType: regional
      namedPorts:
      - name: http
        ports:
        - 80
        - 8080
      scheme: INTERNAL
      serviceName: example-backend-service
    clusterName: example-cluster-name
    controllerClusterId: example-controller-123124
    desiredCapacity: 0
    location: us-central1-a
    maxSize: 2
    minSize: 0
    rootVolumeType: pd-ssd
    shieldedInstanceConfig:
    - enableIntegrityMonitoring: true
      enableSecureBoot: true
    useAsTemplateOnly: false
    whitelist:
    - n1-standard-1
    - n1-standard-2
