apiVersion: oceanawslaunchspec.spot.upbound.io/v1alpha1
kind: OceanAwsLaunchSpec
metadata:
  annotations:
    meta.upbound.io/example-id: oceanawslaunchspec/v1alpha1/oceanawslaunchspec
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    associatePublicIpAddress: true
    autoscaleDown:
    - maxScaleDownPercentage: 20
    autoscaleHeadrooms:
    - cpuPerUnit: 1000
      gpuPerUnit: 0
      memoryPerUnit: 2048
      numOfUnits: 5
    autoscaleHeadroomsAutomatic:
    - autoHeadroomPercentage: 5
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
      - deleteOnTermination: "true"
        dynamicVolumeSize:
        - baseSize: 50
          resource: CPU
          sizePerResourceUnit: 20
        encrypted: "false"
        throughput: 500
        volumeSize: 50
        volumeType: gp2
    createOptions:
    - initialNodes: 1
    deleteOptions:
    - deleteNodes: true
      forceDelete: true
    elasticIpPool:
    - tagSelector:
      - tagKey: key
        tagValue: value
    ephemeralStorage:
    - ephemeralStorageDeviceName: /dev/xvda
    iamInstanceProfile: iam-profile
    imageId: ami-123456
    images:
    - imageId: ami-id1
    - imageId: ami-id2
    instanceMetadataOptions:
    - httpPutResponseHopLimit: 10
      httpTokens: required
    instanceTypes:
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    labels:
    - key: key1
      value: value1
    name: example
    oceanId: o-123456
    preferredOdTypes:
    - c3.large
    - m4.large
    preferredSpotTypes:
    - m4.large
    - m4.xlarge
    resourceLimits:
    - maxInstanceCount: 4
      minInstanceCount: 0
    restrictScaleDown: true
    rootVolumeSize: 30
    schedulingShutdownHours:
    - isEnabled: true
      timeWindows:
      - Sat:08:00-Sat:08:30
      - Sun:08:00-Sun:08:30
    schedulingTask:
    - cronExpression: 0 1 * * *
      isEnabled: true
      taskHeadroom:
      - cpuPerUnit: 1000
        gpuPerUnit: 0
        memoryPerUnit: 2048
        numOfUnits: 5
      taskType: manualHeadroomUpdate
    securityGroups:
    - sg-987654321
    strategy:
    - drainingTimeout: 300
      spotPercentage: 70
      utilizeCommitments: false
      utilizeReservedInstances: true
    subnetIds:
    - subnet-1234
    tags:
    - key: Env
      value: production
    taints:
    - effect: NoExecute
      key: key1
      value: value1
    userData: echo Hello, world!
