apiVersion: oceanaws.spot.upbound.io/v1alpha1
kind: OceanAws
metadata:
  name: hello-crossplane
spec:
  forProvider:
    name: hello-crossplane
    controllerId: clusterControllerId
    maxSize: 2
    minSize: 0
    desiredCapacity: 2
    region: us-west-2
    autoscaler:
      - autoscaleDown:
          - maxScaleDownPercentage: 40
        autoscaleIsEnabled: true
        resourceLimits:
          - maxMemoryGib: 1500
            maxVcpu: 750
        autoscaleHeadroom:
          - cpuPerUnit: 1024
            gpuPerUnit: 1
            memoryPerUnit: 512
            numOfUnits: 2
    utilizeCommitments: false
    clusterOrientation:
      - availabilityVsCost : balanced
    spreadNodesBy : count
    scheduledTask:
      - shutdownHours:
          - isEnabled : false
            timeWindows:
              - Sat:08:00-Sun:08:00
    subnetIds:
      - subnet-12345
      - subnet-54321
    whitelist:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    securityGroups:
      - sg-123456789
    iamInstanceProfile: eks-123456789
    imageId: ami-123456789
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          - deleteOnTermination: true
            encrypted: false
            throughput: 125
            volumeSize: 20
            volumeType: gp3
    tags:
      - key: Env
        value: prod
    instanceMetadataOptions:
      - httpPutResponseHopLimit: 10
        httpTokens: required
  providerConfigRef:
    name: default