apiVersion: oceanrightsizingrule.spot.upbound.io/v1alpha1
kind: OceanRightsizingRule
metadata:
  annotations:
    meta.upbound.io/example-id: oceanrightsizingrule/v1alpha1/oceanrightsizingrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    excludePreliminaryRecommendations: true
    oceanId: o-123456
    recommendationApplicationBoundaries:
    - cpuMax: 190
      cpuMin: 120
      memoryMax: 190
      memoryMin: 160
    recommendationApplicationHpa:
    - allowHpaRecommendations: true
    recommendationApplicationIntervals:
    - repetitionBasis: WEEKLY
      weeklyRepetitionBasis:
      - intervalDays:
        - MONDAY
        - WEDNESDAY
        intervalHoursEndTime: "14:00"
        intervalHoursStartTime: "12:00"
    - monthlyRepetitionBasis:
      - intervalMonths:
        - 2
        - 6
        - 9
        weekOfTheMonth:
        - FIRST
        - LAST
        weeklyRepetitionBasis:
        - intervalDays:
          - MONDAY
          intervalHoursEndTime: "04:00"
          intervalHoursStartTime: "03:00"
      repetitionBasis: MONTHLY
    recommendationApplicationMinThreshold:
    - cpuPercentage: 0.412
      memoryPercentage: 0.36
    recommendationApplicationOverheadValues:
    - cpuPercentage: 0.8
      memoryPercentage: 0.5
    restartReplicas: ALL_MANIFEST
    ruleName: test-rule
